package id.ac.mi.poliban.diana.listviewclubligainggris;

import java.util.ArrayList;
import java.util.List;

public class ClubData {
    static List<Club> getAllClubs(){
        List<Club> data = new ArrayList<>();
        {
            data.add(new Club("https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/180px-Arsenal_FC.svg.png", "Arsenal FC", "Arsenal Football Club is a professional football club based in Islington, London, England, that plays in the Premier League, the top flight of English football. The club has won 13 League titles, a record 13 FA Cups, 2 League Cups, 15 FA Community Shields, 1 League Centenary Trophy, 1 UEFA Cup Winners' Cup and 1 Inter-Cities Fairs Cup."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/en/thumb/7/75/Hereford_United_FC.svg/180px-Hereford_United_FC.svg.png", "Hereford United F.C.", "Hereford United Football Club was an English association football club based in the city of Hereford that last played in the Southern League Premier Division, the seventh tier of English football. Founded in 1924, the club was elected to the Football League in 1972, and spent 31 seasons in the League in two spells, 25 of them in the fourth tier. The club reached the old Second Division in 1976, its best league performance, but was relegated after only one season at that level."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/en/thumb/8/85/Forest_Green_Rovers_crest.svg/200px-Forest_Green_Rovers_crest.svg.png", "Forest Green Rovers F.C.", "Forest Green Rovers Football Club is a professional football club based in Nailsworth, Gloucestershire, England. The team competes in League Two, the fourth tier of English football, and have played their home games at The New Lawn since 2006, when they moved from their original home at The Lawn Ground."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/en/thumb/7/71/Exeter_City_FC.svg/200px-Exeter_City_FC.svg.png", "Exeter City F.C.", "Exeter City Football Club is a professional association football club based in Exeter, Devon, England. The team play in League Two, the fourth tier of the English football league system. Known as the \"Grecians\", the origin of their nickname is subject to speculation and debate. The club is owned by the club's supporters through the Exeter City Supporters' Trust. The club contests West Country derby matches with a number of sides, with Plymouth Argyle being their fiercest rivals."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/180px-Chelsea_FC.svg.png", "Chelsea F.C.", "Chelsea Football Club are an English professional football club based in Fulham, London. Founded in 1905, they compete in the Premier League, the top division of English football. Chelsea are among England's most successful clubs; they have been league champions six times and won over thirty competitive honours, including six European trophies. Their home ground is Stamford Bridge."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Blackpool_FC_logo.svg/180px-Blackpool_FC_logo.svg.png", "Blackpool F.C.", "Blackpool F.C. is an English professional association football club in the seaside town of Blackpool, Lancashire, which competes in League One, the third tier of English football. Founded in 1887, Blackpool's home ground since 1901 has been Bloomfield Road."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Barnsley_FC.svg/200px-Barnsley_FC.svg.png", "Barnsley F.C.", "Barnsley Football Club is a professional association football club based in the town of Barnsley, South Yorkshire, England. The team play in the Championship, the second tier of the English football league system. Nicknamed \"the Tykes\", they were founded in 1887 by Reverend Tiverton Preedy under the name Barnsley St. Peter's. The club's colours were originally blue, but were converted to red and white in 1904 and have played in those colours ever since. Their home ground since 1888 has been Oakwell."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/180px-Liverpool_FC.svg.png", "Liverpool F.C.", "Liverpool Football Club is a professional football club in Liverpool, England, that competes in the Premier League, the top tier of English football. The club has won six European Cups, more than any other English club, three UEFA Cups and four UEFA Super Cups, also English records, eighteen League titles, seven FA Cups, a record eight League Cups and fifteen FA Community Shields."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/180px-Manchester_United_FC_crest.svg.png", "Manchester United F.C.", "Manchester United Football Club is a professional football club based in Old Trafford, Greater Manchester, England, that competes in the Premier League, the top flight of English football. Nicknamed \"the Red Devils\", the club was founded as Newton Heath LYR Football Club in 1878, changed its name to Manchester United in 1902 and moved to its current stadium, Old Trafford, in 1910."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/180px-Liverpool_FC.svg.png", "Liverpool F.C.", "Liverpool Football Club is a professional football club in Liverpool, England, that competes in the Premier League, the top tier of English football. The club has won six European Cups, more than any other English club, three UEFA Cups and four UEFA Super Cups, also English records, eighteen League titles, seven FA Cups, a record eight League Cups and fifteen FA Community Shields."));
        }

        return  data;
    }
}
